server:
  port: 8186
  forward-headers-strategy: framework

spring:
  application:
    name: image-service

minio:
  url: http://minio:9000
  accessKey: tinder
  secretKey: tindertinder
  public-url: ${MINIO_SERVICE_PUBLIC_ENDPOINT:http://localhost:9000}
  bucket-name: profile-images

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'